# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.0
_src_path: gh:radio-aktywne/template-package-python
accountname: radio-aktywne
description: Task scheduler package for Python 🐍
docs: true
docsurl: https://radio-aktywne.github.io/pyscheduler
importname: pyscheduler
packagename: pyscheduler
releases: true
reponame: pyscheduler
repourl: https://github.com/radio-aktywne/pyscheduler
